import 'package:flutter_screenutil/flutter_screenutil.dart';
import '../features/football_api/models/odds/bet.dart';


class DefaultValues {
  DefaultValues._();

  static final double padding = 16.0.h;
  static final double spacing = 16.0.h;
  static final double radius = 20.h;
  static final double buttonHeight = 45.h;

  static const int bannerAdInterval = 15;
  static const int interstitialAdInterval = 5;

  static const int defaultBookmakerId = 11; //1xBet

  static final List<Bet> availableTipsBets = [
    Bet(id: 1, name: 'Match Winner'),
    Bet(id: 2, name: 'Home/Away'),
    Bet(id: 3, name: 'Second Half Winner'),
    Bet(id: 4, name: 'Asian Handicap'),
    Bet(id: 5, name: 'Goals Over/Under'),
    Bet(id: 6, name: 'Goals Over/Under First Half'),
    Bet(id: 7, name: 'HT/FT Double'),
    Bet(id: 8, name: 'Both Teams Score'),
    Bet(id: 9, name: 'Handicap Result'),
    Bet(id: 10, name: 'Exact Score'),
    Bet(id: 11, name: 'Highest Scoring Half'),
    Bet(id: 12, name: 'Double Chance'),
    Bet(id: 13, name: 'First Half Winner'),
    Bet(id: 14, name: 'Team To Score First'),
    Bet(id: 15, name: 'Team To Score Last'),
    Bet(id: 16, name: 'Total - Home'),
    Bet(id: 17, name: 'Total - Away'),
    Bet(id: 18, name: 'Handicap Result - First Half'),
    Bet(id: 19, name: 'Asian Handicap First Half'),
    Bet(id: 20, name: 'Double Chance - First Half'),
    Bet(id: 21, name: 'Odd/Even'),
    Bet(id: 22, name: 'Odd/Even - First Half'),
    Bet(id: 23, name: 'Home Odd/Even'),
    Bet(id: 24, name: 'Results/Both Teams Score'),
    Bet(id: 25, name: 'Result/Total Goals'),
    Bet(id: 26, name: 'Goals Over/Under - Second Half'),
    Bet(id: 27, name: 'Clean Sheet - Home'),
    Bet(id: 28, name: 'Clean Sheet - Away'),
    Bet(id: 29, name: 'Win to Nil - Home'),
    Bet(id: 30, name: 'Win to Nil - Away'),
    Bet(id: 31, name: 'Correct Score - First Half'),
    Bet(id: 32, name: 'Win Both Halves'),
    Bet(id: 33, name: 'Double Chance - Second Half'),
    Bet(id: 34, name: 'Both Teams Score - First Half'),
    Bet(id: 35, name: 'Both Teams To Score - Second Half'),
    Bet(id: 36, name: 'Win To Nil'),
    Bet(id: 37, name: 'Home win both halves'),
    Bet(id: 38, name: 'Exact Goals Number'),
    Bet(id: 39, name: 'To Win Either Half'),
    Bet(id: 40, name: 'Home Team Exact Goals Number'),
    Bet(id: 41, name: 'Away Team Exact Goals Number'),
    Bet(id: 42, name: 'Second Half Exact Goals Number'),
    Bet(id: 43, name: 'Home Team Score a Goal'),
    Bet(id: 44, name: 'Away Team Score a Goal'),
    Bet(id: 45, name: 'Corners Over Under'),
    Bet(id: 46, name: 'Exact Goals Number - First Half'),
    Bet(id: 47, name: 'Winning Margin'),
    Bet(id: 48, name: 'To Score In Both Halves By Teams'),
    Bet(id: 49, name: 'Total Goals/Both Teams To Score'),
    Bet(id: 50, name: 'Goal Line'),
    Bet(id: 51, name: 'Halftime Result/Total Goals'),
    Bet(id: 52, name: 'Halftime Result/Both Teams Score'),
    Bet(id: 53, name: 'Away win both halves'),
    Bet(id: 54, name: 'First 10 min Winner'),
    Bet(id: 55, name: 'Corners 1x2'),
    Bet(id: 56, name: 'Corners Asian Handicap'),
    Bet(id: 57, name: 'Home Corners Over/Under'),
    Bet(id: 58, name: 'Away Corners Over/Under'),
    Bet(id: 59, name: 'Own Goal'),
    Bet(id: 60, name: 'Away Odd/Even'),
    Bet(id: 61, name: 'To Qualify'),
    Bet(id: 62, name: 'Correct Score - Second Half'),
    Bet(id: 63, name: 'Odd/Even - Second Half'),
    Bet(id: 72, name: 'Goal Line (1st Half)'),
    Bet(id: 73, name: 'Both Teams to Score 1st Half - 2nd Half'),
    Bet(id: 74, name: '10 Over/Under'),
    Bet(id: 75, name: 'Last Corner'),
    Bet(id: 76, name: 'First Corner'),
    Bet(id: 77, name: 'Total Corners (1st Half)'),
    Bet(id: 78, name: 'RTG_H1'),
    Bet(id: 79, name: 'Cards European Handicap'),
    Bet(id: 80, name: 'Cards Over/Under'),
    Bet(id: 81, name: 'Cards Asian Handicap'),
    Bet(id: 82, name: 'Home Team Total Cards'),
    Bet(id: 83, name: 'Away Team Total Cards'),
    Bet(id: 84, name: 'Total Corners (3 way) (1st Half)'),
    Bet(id: 85, name: 'Total Corners (3 way)'),
    Bet(id: 86, name: 'RCARD'),
    Bet(id: 87, name: 'Total ShotOnGoal'),
    Bet(id: 88, name: 'Home Total ShotOnGoal'),
    Bet(id: 89, name: 'Away Total ShotOnGoal'),
    Bet(id: 91, name: 'Total Goals (3 way)'),
    Bet(id: 92, name: 'Anytime Goal Scorer'),
    Bet(id: 93, name: 'First Goal Scorer'),
    Bet(id: 94, name: 'Last Goal Scorer'),
    Bet(id: 95, name: 'To Score Two or More Goals'),
    Bet(id: 96, name: 'Last Goal Scorer'),
    Bet(id: 97, name: 'First Goal Method'),
    Bet(id: 99, name: 'To Score A Penalty'),
    Bet(id: 100, name: 'To Miss A Penalty'),
    // Bet(id: 101, name: null),
    Bet(id: 102, name: 'Player to be booked'),
    Bet(id: 103, name: 'Player to be Sent Off'),
    Bet(id: 104, name: 'Asian Handicap (2nd Half)'),
    Bet(id: 105, name: 'Home Team Total Goals(1st Half)'),
    Bet(id: 106, name: 'Away Team Total Goals(1st Half)'),
    Bet(id: 107, name: 'Home Team Total Goals(2nd Half)'),
    Bet(id: 108, name: 'Away Team Total Goals(2nd Half)'),
    Bet(id: 109, name: 'Draw No Bet (1st Half)'),
    Bet(id: 110, name: 'Scoring Draw'),
    Bet(id: 111, name: 'Home team will score in both halves'),
    Bet(id: 112, name: 'Away team will score in both halves'),
    Bet(id: 113, name: 'Both Teams To Score in Both Halves'),
    Bet(id: 114, name: 'Home Team Score a Goal (1st Half)'),
    Bet(id: 115, name: 'Home Team Score a Goal (2nd Half)'),
    Bet(id: 116, name: 'Away Team Score a Goal (1st Half)'),
    Bet(id: 117, name: 'Away Team Score a Goal (2nd Half)'),
    Bet(id: 118, name: 'Home Win/Over'),
    Bet(id: 119, name: 'Home Win/Under'),
    Bet(id: 120, name: 'Away Win/Over'),
    Bet(id: 121, name: 'Away Win/Under'),
    Bet(id: 122, name: 'Home team will win either half'),
    Bet(id: 123, name: 'Away team will win either half'),
    Bet(id: 124, name: 'Home Come From Behind and Win'),
    Bet(id: 125, name: 'Corners Asian Handicap (1st Half)'),
    Bet(id: 126, name: 'Corners Asian Handicap (2nd Half)'),
    Bet(id: 127, name: 'Total Corners (2nd Half)'),
    Bet(id: 128, name: 'Total Corners (3 way) (2nd Half)'),
    Bet(id: 129, name: 'Away Come From Behind and Win'),
    Bet(id: 130, name: 'Corners 1x2 (1st Half)'),
    Bet(id: 131, name: 'Corners 1x2 (2nd Half)'),
    Bet(id: 132, name: 'Home Total Corners (1st Half)'),
    Bet(id: 133, name: 'Home Total Corners (2nd Half)'),
    Bet(id: 134, name: 'Away Total Corners (1st Half)'),
    Bet(id: 135, name: 'Away Total Corners (2nd Half)'),
    Bet(id: 136, name: '1x2 - 15 minutes'),
    Bet(id: 137, name: '1x2 - 60 minutes'),
    Bet(id: 138, name: '1x2 - 75 minutes'),
    Bet(id: 139, name: '1x2 - 30 minutes'),
    Bet(id: 140, name: 'DC - 30 minutes'),
    Bet(id: 141, name: 'DC - 15 minutes'),
    Bet(id: 142, name: 'DC - 60 minutes'),
    Bet(id: 143, name: 'DC - 75 minutes'),
    Bet(id: 144, name: 'Goal in 1-15 minutes'),
    Bet(id: 145, name: 'Goal in 16-30 minutes'),
    Bet(id: 146, name: 'Goal in 31-45 minutes'),
    Bet(id: 147, name: 'Goal in 46-60 minutes'),
    Bet(id: 148, name: 'Goal in 61-75 minutes'),
    Bet(id: 149, name: 'Goal in 76-90 minutes'),
    Bet(id: 150, name: 'Home Team Yellow Cards'),
    Bet(id: 151, name: 'Away Team Yellow Cards'),
    Bet(id: 152, name: 'Yellow Asian Handicap'),
    Bet(id: 153, name: 'Yellow Over/Under'),
    Bet(id: 154, name: 'Yellow Double Chance'),
    Bet(id: 155, name: 'Yellow Over/Under (1st Half)'),
    Bet(id: 156, name: 'Yellow Over/Under (2nd Half)'),
    Bet(id: 157, name: 'Yellow Odd/Even'),
    Bet(id: 158, name: 'Yellow Cards 1x2'),
    Bet(id: 159, name: 'Yellow Asian Handicap (1st Half)'),
    Bet(id: 160, name: 'Yellow Asian Handicap (2nd Half)'),
    Bet(id: 161, name: 'Yellow Cards 1x2 (1st Half)'),
    Bet(id: 162, name: 'Yellow Cards 1x2 (2nd Half)'),
    Bet(id: 163, name: 'Penalty Awarded'),
    Bet(id: 164, name: 'Offsides Total'),
    Bet(id: 165, name: 'Offsides 1x2'),
    Bet(id: 166, name: 'Offsides Handicap'),
    Bet(id: 167, name: 'Offsides Home Total'),
    Bet(id: 168, name: 'Offsides Away Total'),
    Bet(id: 169, name: 'Offsides Double Chance'),
    Bet(id: 170, name: 'Fouls. Away Total'),
    Bet(id: 171, name: 'Fouls. Home Total'),
    Bet(id: 172, name: 'Fouls. Double Chance'),
    Bet(id: 173, name: 'Fouls. Total'),
    Bet(id: 174, name: 'Fouls. Handicap'),
    Bet(id: 175, name: 'Fouls. 1x2'),
    Bet(id: 176, name: 'ShotOnTarget 1x2'),
    Bet(id: 177, name: 'ShotOnTarget Handicap'),
    Bet(id: 178, name: 'ShotOnTarget Double Chance'),
    Bet(id: 179, name: 'First Team to Score'),
    Bet(id: 180, name: 'Last Team to Score'),
    Bet(id: 181, name: 'European Handicap (2nd Half)'),
    Bet(id: 182, name: 'Draw No Bet (2nd Half)'),
    Bet(id: 183, name: 'Double Chance/Total'),
    Bet(id: 184, name: 'To Score in Both Halves'),
    Bet(id: 185, name: 'First Team to Score (3 way) 1st Half'),
    Bet(id: 186, name: 'Total Goals Number By Ranges'),
    Bet(id: 187, name: 'Total Goals By Ranges (1st Half)'),
    Bet(id: 188, name: 'Clean Sheet'),
    Bet(id: 189, name: 'To Advance Handicap'),
    Bet(id: 190, name: 'Home Exact Goals Number (1st Half)'),
    Bet(id: 191, name: 'Away Exact Goals Number (1st Half)'),
  ];
}